### ISSUE TITLE
how to fix opening Direct 3D Output window

### ISSUE THREAD

**Issue by kadan-dev** [alexmercerind/dart_vlc#201]
I want to play video on screen
<img width="757" alt="Screenshot_1" src="https://user-images.githubusercontent.com/61644490/145525641-050ab022-fa09-486a-a81c-e93565748ec5.png">

**Comment by alexmercerind** [comment]
Can you please share your code in a repository? It should not happen.

**Comment by kadan-dev** [comment]
> Can you please share your code in a repository? It should not happen.
> 
> Also share the URL.

```
import 'package:dart_vlc/dart_vlc.dart';
import 'package:flutter/material.dart';

class HomeScreen extends StatefulWidget {
  HomeScreen({Key? key}) : super(key: key);

  @override
  _nameState createState() => _nameState();
}

class _nameState extends State<HomeScreen> {
  Player player = Player(id: 0);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Title'),
      ),
      body: Column(
        children: [
          Card(
            clipBehavior: Clip.antiAlias,
            elevation: 2.0,
            child: Video(
              showControls: false,
              // filterQuality: ,
              player: player,
              width: 640,
              height: 480,
              volumeThumbColor: Colors.blue,
              volumeActiveColor: Colors.blue,
            ),
          ),
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceEvenly,
            children: [
              ElevatedButton(
                onPressed: () => this.setState(
                  () {
                    this.player.open(
                          Media.network(
                              'https://svs.itworkscdn.net/rudawlive/rudawlive.smil/playlist.m3u8'),
                        );
                  },
                ),
                child: Text(
                  'play url',
                  style: TextStyle(
                    fontSize: 14.0,
                  ),
                ),
              ),
              ElevatedButton(
                onPressed: () => this.player.stop(),
                child: Text(
                  'stop url',
                  style: TextStyle(
                    fontSize: 14.0,
                  ),
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }
}

```

**Comment by kadan-dev** [comment]
> Can you please share your code in a repository? It should not happen.
> 
> Also share the URL.
need help?

**Comment by wilz05** [comment]
similar above examples doesn't work on macos as well, just gives player with empty screen but audio is playing

**Comment by alexmercerind** [comment]
> similar above examples doesn't work on macos as well, just gives player with empty screen but audio is playing

I fixed this in d56e2438eee6258933effb2f29c4e74fa6f99365. Could you make the changes locally & test?

**Comment by wilz05** [comment]
> 

I am kinda new to this git   
```
dart_vlc: 
    git:
      url: https://github.com/alexmercerind/dart_vlc.git
      ref: d56e243
```

when I link the above repo in my yaml file,  getting below error 
```

Error on line 16, column 11: Invalid description in the "dart_vlc" pubspec on the "dart_vlc_ffi" dependency: "./ffi" is a relative path, but this isn't a local pubspec.
   ╷
16 │     path: ./ffi
   │           ^^^^^
   ╵
pub get failed (65;    ╵)
Process finished with exit code 65
```

**Comment by alexmercerind** [comment]
> > 
> 
> I am kinda new to this git
> 
> ```
> dart_vlc: 
>     git:
>       url: https://github.com/alexmercerind/dart_vlc.git
>       ref: d56e243
> ```
> 
> when I link the above repo in my yaml file, getting below error
> 
> ```
> 
> Error on line 16, column 11: Invalid description in the "dart_vlc" pubspec on the "dart_vlc_ffi" dependency: "./ffi" is a relative path, but this isn't a local pubspec.
>    ╷
> 16 │     path: ./ffi
>    │           ^^^^^
>    ╵
> pub get failed (65;    ╵)
> Process finished with exit code 65
> ```

You can't use git version of the plugin... It's a known problem. Make changes locally. I will remove submodules in future to fix this.

**Comment by wilz05** [comment]
no still no luck with local clone
#include <vlcpp/vlc.hpp>
         ^~~~~~~~~~~~~~~

1 error generated.
make[2]: *** [CMakeFiles/dart_vlc_core.dir/main.cc.o] Error 1
make[1]: *** [CMakeFiles/dart_vlc_core.dir/all] Error 2
make: *** [all] Error 2
Command PhaseScriptExecution failed with a nonzero exit code
note: Using new build system
note: Planning
note: Build preparation complete
note: Building targets in dependency order
** BUILD FAILED **

Exception: Build process failed

**Comment by zezo357** [comment]
> > similar above examples doesn't work on macos as well, just gives player with empty screen but audio is playing
> 
> I fixed this in [d56e243](https://github.com/alexmercerind/dart_vlc/commit/d56e2438eee6258933effb2f29c4e74fa6f99365). Could you make the changes locally & test?

i will wait for that update since i need it too
and couldnt do the changes locally

**Comment by zezo357** [comment]
@alexmercerind  can this fix be published as a prerelease since i tried to change the files but failed

**Comment by zezo357** [comment]
ok i did successfully made the changes 
but i see two problems
1. video has black area on the left (looks like the video is shifted to the right) 
2. play time sometimes goes 1 sec and sometimes goes 2 and video lags (sound and video for 0.5 sec and countines back to normal for like 5 sec )

**Comment by zezo357** [comment]
> ok i did successfully made the changes but i see two problems
> 
> 1. video has black area on the left (looks like the video is shifted to the right)
> 2. play time sometimes goes 1 sec and sometimes goes 2 and video lags (sound and video for 0.5 sec and countines back to normal for like 5 sec )

but the output windows (the main problem got fixed)
